#[cfg(feature = "iced-ui")]
use std::{fs, path::PathBuf};

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        let mut resource = winres::WindowsResource::new();
        resource.set_icon("assets/icons/ico/socd-light.ico");
        resource
            .compile()
            .expect("failed to embed the LastKey application icon");
        // The generated pixels are read only by `src/ui/app.rs`, which is
        // behind the same feature, so the decode and its dependency belong
        // to it as well.
        #[cfg(feature = "iced-ui")]
        extract_window_icon();
    }
}

/// Unpacks the 32x32 PNG layer from the application ICO and emits it as RGBA
/// bytes for the Iced-native window icon (`iced::window::icon::from_rgba`).
/// The checked-in ICO stores every layer PNG-compressed, so extraction is a
/// byte slice plus a PNG decode. Build-time only, keeping the resident
/// runtime dependency graph unchanged.
#[cfg(feature = "iced-ui")]
fn extract_window_icon() {
    const ICON_WIDTH: u32 = 32;
    const ICON_HEIGHT: u32 = 32;

    let ico = fs::read("assets/icons/ico/socd-light.ico").expect("window icon ICO is missing");
    let png = square_png_layer(&ico, ICON_WIDTH).expect("window icon PNG layer is missing");

    let decoder = png::Decoder::new(std::io::Cursor::new(png));
    let mut reader = decoder.read_info().expect("window icon PNG is invalid");
    let mut rgba = vec![
        0;
        reader
            .output_buffer_size()
            .expect("window icon size is known")
    ];
    let info = reader
        .next_frame(&mut rgba)
        .expect("window icon PNG is invalid");
    assert!(
        info.width == ICON_WIDTH
            && info.height == ICON_HEIGHT
            && info.color_type == png::ColorType::Rgba
            && info.bit_depth == png::BitDepth::Eight,
        "window icon PNG must be 32x32 8-bit RGBA",
    );
    rgba.truncate(info.buffer_size());

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set"));
    // Pixels travel as a byte blob, not as thousands of integer literals: the
    // dimensions keep their single source of truth in the generated source.
    fs::write(out_dir.join("lastkey_icon.rgba"), &rgba).expect("window icon output is writable");
    fs::write(
        out_dir.join("lastkey_icon.rs"),
        format!(
            "// Generated by build.rs from assets/icons/ico/socd-light.ico; do not edit.\n\
             pub const WINDOW_ICON_WIDTH: u32 = {ICON_WIDTH};\n\
             pub const WINDOW_ICON_HEIGHT: u32 = {ICON_HEIGHT};\n\
             pub const WINDOW_ICON_RGBA: &[u8] =\n\
             include_bytes!(concat!(env!(\"OUT_DIR\"), \"/lastkey_icon.rgba\"));\n"
        ),
    )
    .expect("window icon output is writable");
    println!("cargo:rerun-if-changed=assets/icons/ico/socd-light.ico");
}

/// Returns the raw PNG bytes of the `size`x`size` layer in a PNG-compressed
/// ICO file: a six-byte header, sixteen-byte directory entries, then the
/// image blobs the entries point at.
#[cfg(feature = "iced-ui")]
fn square_png_layer(ico: &[u8], size: u32) -> Option<&[u8]> {
    if ico.get(2..4) != Some(&[1, 0]) {
        return None;
    }
    let entry_count = u16::from_le_bytes(ico.get(4..6)?.try_into().ok()?) as usize;
    let wanted = if size == 256 {
        0
    } else {
        u8::try_from(size).ok()? as usize
    };
    for index in 0..entry_count {
        let entry = ico.get(6 + index * 16..6 + (index + 1) * 16)?;
        let entry_width = usize::from(entry[0]);
        let entry_height = usize::from(entry[1]);
        let blob_size = u32::from_le_bytes(entry[8..12].try_into().ok()?) as usize;
        let offset = u32::from_le_bytes(entry[12..16].try_into().ok()?) as usize;
        if entry_width == wanted && entry_height == wanted {
            let blob = ico.get(offset..offset + blob_size)?;
            // PNG-compressed layers start with the PNG signature; BMP layers
            // start with a BITMAPINFOHEADER and need a different decoder.
            if blob.starts_with(&[0x89, b'P', b'N', b'G']) {
                return Some(blob);
            }
            return None;
        }
    }
    None
}
