#pragma once

#ifndef LASTKEY_VERSION_MAJOR
#define LASTKEY_VERSION_MAJOR 1
#endif
#ifndef LASTKEY_VERSION_MINOR
#define LASTKEY_VERSION_MINOR 0
#endif
#ifndef LASTKEY_VERSION_PATCH
#define LASTKEY_VERSION_PATCH 0
#endif
#ifndef LASTKEY_VERSION_BUILD
#define LASTKEY_VERSION_BUILD 0
#endif

#define LASTKEY_STRINGIFY_IMPL(value) #value
#define LASTKEY_STRINGIFY(value) LASTKEY_STRINGIFY_IMPL(value)
#define LASTKEY_VERSION_TEXT \
    LASTKEY_STRINGIFY(LASTKEY_VERSION_MAJOR) "." \
    LASTKEY_STRINGIFY(LASTKEY_VERSION_MINOR) "." \
    LASTKEY_STRINGIFY(LASTKEY_VERSION_PATCH)
